### ISSUE TITLE
The plug-in failed to start

### ISSUE THREAD

**Issue by ghost** [soanseng/vocbuilderAI#1]
anki version
https://github.com/ankitects/anki/releases/download/23.12.1/anki-23.12.1-windows-qt6.exe
error message
```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading vocbuilderAI:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\owowe\AppData\Roaming\Anki2\addons21\1754806193\__init__.py", line 27, in <module>
    from openai import OpenAI
  File "C:\Users\owowe\AppData\Roaming\Anki2\addons21\1754806193\libs\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\Users\owowe\AppData\Roaming\Anki2\addons21\1754806193\libs\openai\types\__init__.py", line 5, in <module>
    from .edit import Edit as Edit
  File "C:\Users\owowe\AppData\Roaming\Anki2\addons21\1754806193\libs\openai\types\edit.py", line 6, in <module>
    from .._models import BaseModel
  File "C:\Users\owowe\AppData\Roaming\Anki2\addons21\1754806193\libs\openai\_models.py", line 20, in <module>
    from pydantic.fields import FieldInfo
  File "C:\Users\owowe\AppData\Roaming\Anki2\addons21\1754806193\libs\pydantic\fields.py", line 21, in <module>
    from pydantic_core import PydanticUndefined
  File "C:\Users\owowe\AppData\Roaming\Anki2\addons21\1754806193\libs\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
```

**Comment by CKLove47** [comment]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19041

When loading vocbuilderAI:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1754806193\__init__.py", line 27, in <module>
    from openai import OpenAI
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1754806193\libs\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1754806193\libs\openai\types\__init__.py", line 5, in <module>
    from .edit import Edit as Edit
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1754806193\libs\openai\types\edit.py", line 6, in <module>
    from .._models import BaseModel
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1754806193\libs\openai\_models.py", line 20, in <module>
    from pydantic.fields import FieldInfo
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1754806193\libs\pydantic\fields.py", line 21, in <module>
    from pydantic_core import PydanticUndefined
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1754806193\libs\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'


same problem

**Comment by soanseng** [comment]
I fix it. I drop the openai dependency, please use version 0.4

**Comment by CKLove47** [comment]
Thank bro從 Windows 的郵件傳送 寄件者: Soanseng Tan傳送時間: 2024年4月24日 11:04收件者: soanseng/vocbuilderAI副本: CKLove47; Comment主旨: Re: [soanseng/vocbuilderAI] The plug-in failed to start (Issue #1) I fix it. I drop the openai dependency, please use version 0.4—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
